Name: RightLink 10.6.0 Windows Base
Description: |
  Base ServerTemplate for RightLink10. RightLink10 is a new agent to connect
  servers to the RightScale platform that is very lightweight and simple to
  install. _It is not a plug-in upgrade from the older RightLink v6 or prior
  versions._ See [http://docs.rightscale.com/rl/about.html](http://docs.rightscale.com/rl/about.html)
  for details.

  This base ST includes a few boot scripts that:

  * Wait for an EIP to settle (AWS only)
  * Sets up RightLink10 automatic upgrades
  * Enables RightScale OS monitoring.

  It has an operational script to force a RightLink10 upgrade. And we also
  provide a decommission script that provides the reason for shutdown. The
  source of the scripts on this ServerTemplate is available at
  [https://github.com/rightscale/rightlink_scripts/tree/10.6.0](https://github.com/rightscale/rightlink_scripts/tree/10.6.0).

  __Tested Windows distros:__

  * Windows Server 2008R2
  * Windows Server 2012
  * Windows Server 2012R2
  * Windows Server 2016

  __Tested compute clouds:__

  * AWS
  * Azure RM
  * Google Compute Engine
  * Softlayer
  * OpenStack
  * RCA-V (VMware)

  __Tested use cases:__

  * Install-At-Boot
  * Enable-Running
  * Custom-Image

  __This ServerTemplate is only meant to be used to enable existing servers or
  to boot up new custom created images via RightScale. It is not intended to be
  booted with the included images, they are only supplied as reference for what
  was used for validation.__

  The images included are stock/official images made available by the cloud
  provider or the OS developer. Therefore they can be deregistered and made
  unavailable at any time at the discretion of the owner. It is advised that you
  create your own MultiCloud Image with your own custom image for Linux or
  Windows. Please refer to [http://docs.rightscale.com/rl10/reference/rl10_os_compatibility.html#rightscale-tested-images](http://docs.rightscale.com/rl10/reference/rl10_os_compatibility.html#rightscale-tested-images)

  Some of the images included may require you to accept terms of service before
  using the image. Please follow the instructions provided in the error message
  during launch or refer to the OS compatibility link above.
Inputs: {}
RightScripts:
  Boot:
  - wait-for-eip.ps1
  - setup-ntp.ps1
  - setup-automatic-upgrade.ps1
  - enable-monitoring.ps1
  - setup-alerts.ps1
  Operational:
  - upgrade.ps1
  - setup-automatic-upgrade.ps1
  Decommission:
  - shutdown-reason.ps1
MultiCloudImages:
- Name: Windows_Server_Standard_2012R2_x64
- Name: Windows_Server_Datacenter_2012R2_x64
- Name: Windows_Server_Standard_2012_x64
- Name: Windows_Server_Standard_2016_x64
- Name: Windows_Server_Datacenter_2012_x64
- Name: Windows_Server_Datacenter_2008R2_x64
- Name: Windows_Server_Datacenter_2016
Alerts:
- Name: rs instance terminated
  Description: The instance has been terminated anormally, i.e., not through the RightScale
    interface or by an elasticity deamon (only for server arrays).
  Clause: If RS/server.state == terminated for 1 minutes Then escalate critical
- Name: rs instance stranded
  Description: Raises an alert if the instance enters the stranded state.
  Clause: If RS/server-failure.state == stranded for 1 minutes Then escalate warning
- Name: rs instance not responding
  Description: It raises an alert if the instance fials to send monitoring information
    for 5 minutes.
  Clause: If cpu-0/cpu-idle.value == NaN for 5 minutes Then escalate critical
- Name: rs cpu busy
  Description: Raise an alert if the idle time is too low
  Clause: If cpu-0/cpu-idle.value < 15 for 3 minutes Then escalate warning
- Name: rs cpu overloaded
  Description: Raises an alert when the cpu idle time is too low.
  Clause: If cpu-0/cpu-idle.value < 3 for 5 minutes Then escalate critical
- Name: 'rs low space on C: drive'
  Description: 'Raises an alert if the available space on the C: drive is too low'
  Clause: If df-C/df_complex-free.value < 1073741824 for 5 minutes Then escalate critical
- Name: rs high network tx activity
  Description: Raise an alert if the amount of network data transmitted is too high.
    This alert may be modified or cloned on an instance to match the actual network
    interfaces that are present. See the RL10 Windows Setup Alerts RightScript (rlw/setup-alerts.ps1)
    for more details.
  Clause: If interface-AWS_PV_Network_Device_0/if_octets.tx > 10000000 for 10 minutes
    Then escalate critical
- Name: rs high network rx activity
  Description: Raise an alert if the amount of network data received is too high.
    This alert may be modified or cloned on an instance to match the actual network
    interfaces that are present. See the RL10 Windows Setup Alerts RightScript (rlw/setup-alerts.ps1)
    for more details.
  Clause: If interface-AWS_PV_Network_Device_0/if_octets.rx > 50000000 for 30 minutes
    Then escalate critical
- Name: rs memory low
  Description: Free memory is low.
  Clause: If memory/memory-free.value < 1000000 for 1 minutes Then escalate critical
- Name: rs out of memory
  Description: Raises an alert when the server is out of free memory.
  Clause: If memory/memory-free.value == 0 for 1 minutes Then escalate critical
