#! /bin/bash -e

# The server's hostname is set to the longest valid prefix or suffix of
# this SERVER_HOSTNAME variable eg 'my.example.com V2', 'NEW my.example.com', and
# 'database.io my.example.com' all set the hostname to 'my.example.com'.
# If SERVER_HOSTNAME is empty, will maintain current hostname.

if [[ -n "$SERVER_HOSTNAME" ]]; then
  prefix=
  suffix=

  re='^[-A-Za-z0-9_][-A-Za-z0-9_.]*[-A-Za-z0-9_]'
  if [[ "$SERVER_HOSTNAME" =~ $re ]]; then
    prefix=${BASH_REMATCH[0]}
    echo "prefix set to ${prefix}"
  fi
  re='[-A-Za-z0-9_][-A-Za-z0-9._]*[-A-Za-z0-9_]$'
  if [[ "$SERVER_HOSTNAME" =~ $re ]]; then
    suffix=${BASH_REMATCH[0]}
    echo "suffix set to ${suffix}"
  fi

  if (( ${#prefix} >= ${#suffix} && ${#prefix} > 1 )); then
    echo "Setting hostname to prefix '$prefix'"
    hostname="$prefix"
  elif (( ${#suffix} > 1 )); then
    echo "Setting hostname to suffix '$suffix'"
    hostname="$suffix"
  fi

  sudo hostname "$hostname"
fi

# This works around spurious warnings generated by sudo if the hostname can't resolve.
# /etc/sudoers is designed to be able to be distributed among multiple servers.
# Each permission in the /etc/sudoers has a host portion. Sudo does a hostname
# lookup to enforce the host portion, and will throw a warning if it can't
# resolve the hostname in some way.

hostname=$(hostname)
if ! grep "$hostname" /etc/hosts >/dev/null 2>&1; then
  echo "Adding $hostname to /etc/hosts"
  echo "127.0.0.1 $hostname" | sudo tee -a /etc/hosts
fi
